-- === Drop ====

-- 권한
DROP TABLE AUTHORITY CASCADE CONSTRAINT;
-- 회원
DROP TABLE MEMBER CASCADE CONSTRAINT;
-- 관리자
DROP TABLE ADMIN CASCADE CONSTRAINT;
-- 메모
DROP TABLE MY_MEMO CASCADE CONSTRAINT;
DROP SEQUENCE MEMO_ID;
-- 공지사항
DROP TABLE BOARD_NOTICE CASCADE CONSTRAINT;
DROP SEQUENCE BOARD_NOTICE_ID;
-- QnA
DROP TABLE BOARD_QNA CASCADE CONSTRAINT;
DROP SEQUENCE BOARD_QNA_ID;
-- QnA댓글
DROP TABLE COMMENT_QNA CASCADE CONSTRAINT;
DROP SEQUENCE COMMENT_QNA_ID;
-- 자유게시판
DROP TABLE BOARD_FREE CASCADE CONSTRAINT;
DROP SEQUENCE BOARD_FREE_ID;
-- 자게댓글
DROP TABLE COMMENT_FREE CASCADE CONSTRAINT;
DROP SEQUENCE COMMENT_FREE_ID;
-- 레시피공유게시판
DROP TABLE BOARD_SHARE_RECIPE CASCADE CONSTRAINT;
DROP SEQUENCE BOARD_SHARE_RECIPE_ID;
-- 레시피 추천여부
DROP TABLE MEMBER_RECIPE_RECOMMAND CASCADE CONSTRAINT;
DROP SEQUENCE MEMBER_RECIPE_RECOMMAND_KEY;
-- 후기게시판
DROP TABLE BOARD_REVIEW CASCADE CONSTRAINT;
DROP SEQUENCE BOARD_REVIEW_ID;
-- 냉장고
DROP TABLE fridger CASCADE CONSTRAINT;
DROP SEQUENCE fridger_ID;
-- 냉장고 가입처리
DROP TABLE join_process CASCADE CONSTRAINT;
DROP SEQUENCE process_no;
-- 냉장고 공유멤버
DROP TABLE fridger_GROUP CASCADE CONSTRAINT;
DROP SEQUENCE GROUP_KEY;
-- 쇼핑몰
DROP TABLE SHOP CASCADE CONSTRAINT;
DROP SEQUENCE SHOP_ID;
-- 재료관리
DROP TABLE IRDNT_MANAGE CASCADE CONSTRAINT;
DROP SEQUENCE IRDNT_ID;
-- 나의 식재료
DROP TABLE MY_IRDNT CASCADE CONSTRAINT;
DROP SEQUENCE MY_IRDNT_KEY;
-- 공유레시피 재료
DROP TABLE SHARE_RECIPE_IRDNT CASCADE CONSTRAINT;
DROP SEQUENCE SHARE_RECIPE_IRDNT_KEY;
-- 기피재료
DROP TABLE MY_DISLIKE_IRDNT CASCADE CONSTRAINT;
DROP SEQUENCE MY_DISLIKE_IRDNT_KEY;
-- 즐겨찾기
DROP TABLE FAVORITE_RECIPE CASCADE CONSTRAINT;
DROP SEQUENCE FAVORITE_RECIPE_KEY;
-- 레시피 기본정보
DROP TABLE RECIPE_INFO CASCADE CONSTRAINT;
DROP SEQUENCE RECIPE_ID_seq;
-- 레시피 재료정보
DROP TABLE RECIPE_IRDNT CASCADE CONSTRAINT;
DROP SEQUENCE IRDNT_NO_seq;
-- 레시피 과정정보
DROP TABLE RECIPE_CRSE CASCADE CONSTRAINT;
-- 레시피 재료 임시
DROP TABLE RECIPE_IRDNT_TEMP CASCADE CONSTRAINT;


-- ============== Delete ==============

-- 권한
DELETE FROM AUTHORITY;
-- 회원
DELETE FROM MEMBER;
-- 관리자
DELETE FROM ADMIN;
-- 메모
DELETE FROM MY_MEMO;
-- 공지사항
DELETE FROM BOARD_NOTICE;
-- QnA
DELETE FROM BOARD_QNA;
-- QnA댓글
DELETE FROM COMMENT_QNA;
-- 자유게시판
DELETE FROM BOARD_FREE;
-- 자게댓글
DELETE FROM COMMENT_FREE;
-- 레시피공유게시판
DELETE FROM BOARD_SHARE_RECIPE
-- 레시피 추천여부
DELETE FROM MEMBER_RECIPE_RECOMMAND;
-- 후기게시판
DELETE FROM BOARD_REVIEW;
-- 냉장고
DELETE FROM fridger;
-- 냉장고 가입처리
DELETE FROM join_process;
-- 냉장고 공유멤버
DELETE FROM fridger_GROUP;
-- 쇼핑몰
DELETE FROM SHOP;
-- 재료관리
DELETE FROM IRDNT_MANAGE;
-- 나의 식재료
DELETE FROM MY_IRDNT;
-- 공유레시피 재료
DELETE FROM SHARE_RECIPE_IRDNT;
-- 기피재료
DELETE FROM MY_DISLIKE_IRDNT;
-- 즐겨찾기
DELETE FROM FAVORITE_RECIPE;
-- 레시피 기본정보
DELETE FROM RECIPE_INFO;
-- 레시피 재료정보
DELETE FROM RECIPE_IRDNT;
-- 레시피 과정정보
DELETE FROM RECIPE_CRSE;
-- 레시피 재료 임시
DELETE FROM RECIPE_IRDNT_TEMP;
